### PR TITLE
Capstone setup

### PR DESCRIPTION
**Pull request by Paskab012**
### Hello Reviewer🥳
In this React/Redux Capstone project, I have working with :
- Fetch Api from weather API
- Used a required gitflow
- Folloowed the React/Redux best practices
- Displayed the detail page 
## GENERAL REQUIREMENTS
1. You should follow these [design guidelines](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), including:
  - Colors (select one main color for your website).
  - Typography: font face, size and weight.
  - Layout: composition and space between elements.
  - Original design idea by [Nelson Sakwa on Behance](https://www.behance.net/sakwadesignstudio).
  
#### Interactions

1. Home page

When the page loads, the webapp shows the list of categories that could be filtered out by some parameter, for example by the category name.
Along with the category name, you will display some numeric values per category that come from the API.
When the user clicks (or taps) on a category item, the application navigates to the details page.
2. Details page

In the details page, the webapp retrieves data from the API to show detailed data in the category.
When the user clicks on the "Back" button (<), the user navigates to the home page.
Testing requirements

## Create unit tests for pure functions in your Redux code.
  - Create integration tests for your application using the React Testing Library.
  - You may need to mock the access to the API, so that your tests don't send actual requests.
  - You may need to mock the connection to the Redux Store.

Here is the [Loom video](https://www.loom.com/share/8b122832d5f847caa896c021374589c0) for project description.

### CODE REVIEW

**Review by emmanuellekamwa — CHANGES_REQUESTED** [review]
**STATUS: CHANGES REQUESTED 🍾✔🎉**
Hello @Paskab012 👋
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- You documented your work professionally.✔
- Github inline comments feature is used properly.
- You asked for the changes in a friendly and polite way.

## Required Changes ♻️

- When I click on a country, it doesn't show me the details but instead shows me "loading, wait a moment..." and when I check the console I could see that there are errors. Please kindly fix that.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Paskab012** [comment]
Hello @emmanuellekamwa , I went through the codes but I am not actually getting where the error is coming from as in the browser it is not showing. 
## The details page is showing successfully in the browser
Screen Shot 2022-04-23 at 17 10 59

but the one link on netlify is the one having the error, I will continue looking at it but kindly run the project locally.

**Comment by Paskab012** [comment]
Got the error, thanks @emmanuellekamwa .

**Review by codepantha — APPROVED** [review]
Hi @Paskab012 👋,

## STATUS: APPROVED ✔️  

Good job implementing the required changes 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

### To Highlight 🎯 
- Meaningful commit messages ✔️ 
- Beautiful UI ✔️ 
- Descriptive PR ✔️ 
- Linter checks all passing ✔️ 

 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
